### ISSUE TITLE
Caches last longer than 8 minutes

### ISSUE THREAD

**Issue by cchalm** [thomasesmith/kartlaps#10]
A few times now I've done queries several hours apart and found no new data. So I did a controlled test, or as controlled as I could make it anyway. I verified that heat 58593 was available via the v1 api (http://kartlaps.info/tirwashington/heat/58593) and not via the v2 api. I queried heat 58593 twice through the v2 api, half an hour apart, with no queries in between. The second time, there was still no data for the heat. Unless someone else was hitting the heat every eight minutes, caching isn't working as intended.

If it helps for debugging, the two queries were at 2017-10-26 21:41:03 and 2017-10-26 22:14:53. In both cases I actually queried heats 58593-58892, and they all exhibited the same problem.

**Comment by thomasesmith** [comment]
I think I figured out why this was misbehaving. I believe I made a dumb mistake where I use the Memcache::set method. I mixed up in what order the set() method expects its arguments, allowing for caching, but not setting the expiration properly.

I flushed all of the items from the cache in production and put up a fix. Could you possibly do a similar test again?

**Comment by cchalm** [comment]
I scanned for new heats a few times today, and new heats showed up each time. Seems fixed to me

**Comment by thomasesmith** [comment]
Thanks so much for checking! This was a far-reaching problem, so thank you so much for finding it and submitting this issue.
