### ISSUE TITLE
Lap info is returned with data in keys

### ISSUE THREAD

**Issue by cchalm** [thomasesmith/kartlaps#2]
Lap information in v2 (similar for v1) is returned like this:

```
"laps": {
    "75116": {
        "1": { ... },
        "2": { ... },
        ...
    },
    "3900": {
        "1": { ... },
        "2": { ... },
        ...
    },
    ...
}
```

Which is easy on the eyes but difficult to parse. Both racer ID and lap number are in keys, which is inconvenient for a few reasons:
- The only way to validate keys in JSON schema is with regex, the built-in integer type is not applicable
- Clients must parse the keys to integers manually, whereas JSON parsers will do it automatically with JSON values
- The keys are not known until they are examined, forcing clients to iterate over the object assigned to the "laps" property as if it is an array

While the existing structure works, it would be easier to validate and parse in this arrangement:

```
"racerLaps": [{
    "racerId": 75116,
    "laps": [{
        "lapNumber": 1,
        ...
    }, {
        "lapNumber": 2,
        ...
    }]
}, {
    "racerId": 3900,
    "laps": [{
        "lapNumber": 1,
        ...
    }, {
        "lapNumber": 2,
        ...
    }]
}, {
...
}]
```

You could also remove the "lapNumber" property and instead guarantee that the first entry of the array is always lap 1, second entry always lap 2, etc. Not sure which way is best practice.

**Comment by thomasesmith** [comment]
Thank you so much for this thoughtful explanation. And I understand. I can make these changes.

**Comment by thomasesmith** [comment]
I have changed this in production, and updated the source in this repo to reflect it. The lap data on /v2 Heat requests is now outputted more semantically and easier for you to parse. Please confirm. Thanks.

**Comment by cchalm** [comment]
Looks good, thanks for being open to this idea and for the quick resolution
