### ISSUE TITLE
In v1, racer query's "best_time" value is incorrect

### ISSUE THREAD

**Issue by cchalm** [thomasesmith/kartlaps#3]
http://kartlaps.info/tirwashington/racer/1160598

The above query returns:

```
{
    location: "tirwashington",
    racer_id: "1160598",
    uri: "http://kartlaps.info/tirwashington/racer/1160598",
    racer_name: "Ry guy",
    points: 1165,
    heats: [
    {
        heat_name: "Indoor Drop-In - Kart 5",
        heat_id: 57971,
        kart_number: 5,
        date_time_local: "10/13/2017 12:10 PM",
        final_position: 22,
        points_effect: 5,
        final_points: 1160,
        best_time: 1160,      <----- not correct
        uri: "http://kartlaps.info/tirwashington/heat/57971"
    },
    ...
}
```

Note that "best_time" is 1160. "best_time" for this track should be approximately in the range [18, 40]. All racer queries seem to have this problem.

**Comment by thomasesmith** [comment]
Actually, I can see in your example that a few of those values are jumbled around and put in the wrong place. This is an effect of yesterday's issues. 

I just fixed this in production. Please confirm. Thank you.

**Comment by cchalm** [comment]
Confirmed, values now look correct
