### ISSUE TITLE
v2 heat query missing laps for one participant

### ISSUE THREAD

**Issue by cchalm** [thomasesmith/kartlaps#4]
The following v2 query returns no lap information for racer with ID 1100188:
http://kartlaps.info/v2/tirwashington/heat/2275

```
laps: [
  {
    racerId: 1098676,
    racerLaps: [
      ...
    ]
  },
  {
    racerId: 1100188
    // racerLaps missing
  },
  ...
]
```

The source it pulls from does have lap information for that participant:
http://tirwashington.clubspeedtiming.com/sp_center/HeatDetails.aspx?HeatNo=2275

And the v1 query does return that lap information:
http://kartlaps.info/tirwashington/heat/2275

**Comment by thomasesmith** [comment]
I will investigate this tonight and answer back. Thank you.

**Comment by thomasesmith** [comment]
The XPath query to find this racer's lap times on the heat page isn't executing properly because the racer used double quotes in their racer name. I am going to make a change to the code tonight to handle this possibility. Thanks.

**Comment by thomasesmith** [comment]
I have pushed a fix for this to production. Please confirm. Thanks, @cchalm.

**Comment by cchalm** [comment]
Laps are there now, looks good. Thanks
