### ISSUE TITLE
Racers with empty names do not have "racerName" property in heat participant list

### ISSUE THREAD

**Issue by cchalm** [thomasesmith/kartlaps#5]
https://kartlaps.info/v2/tirwashington/heat/50628

The above heat contains three racers whose names are empty strings. This is a subjective issue - racers with empty names have no "racerName" property, rather than having a name property set to an empty string, e.g.:

```
participants: [
  ...
  {
    url: "https://kartlaps.info/v2/tirwashington/racer/1174450",
    id: 1174450
    // racerName missing
  },
  ...
]
```

The data is easier to validate if racerName is a required property. Note that the v1 api's response does include the racerName property. The behavior changed in v2.

**Comment by cchalm** [comment]
"racerName" is also missing from the racer query:

https://kartlaps.info/v2/tirwashington/racer/1174450

**Comment by thomasesmith** [comment]
Good catch. I have fixed this in production.

But it does demonstrate an even bigger problem; when racer names are empty strings, it is difficult for the Heat object to scrape the individual laps of that racer. And it demonstrates that if two or more racers in the same heat have identical racer names, the API fudges collecting their laps. I will go in to more detail on this in the additional Issues you've created on the subject.
