### ISSUE TITLE
Missing laps are recorded as 0 seconds

### ISSUE THREAD

**Issue by cchalm** [thomasesmith/kartlaps#7]
https://kartlaps.info/v2/tirwashington/heat/12345

Minor issue, maybe not worth fixing. This is kind of the opposite of the racerName property issue. If a racer does not get to lap 21 in their race, I expect lap 21 to simply be absent from the data. Instead, it is reported as a zero-second lap:

```
{
  lapNumber: 21,
  seconds: 0,
  position: 0
},
```

The client can filter these out, of course, but it would be cleaner to not have to.

**Comment by thomasesmith** [comment]
I tend to agree here that those extra laps can be left off of the output. I have adjusted this in production. Thanks.
